### ISSUE TITLE
Create docs with resource descriptions

### ISSUE THREAD

**Issue by max-lobur** [dihedron/terraform-provider-jenkins#3]

**Comment by dihedron** [comment]
Yes, you're right documentation is lacking. I'm going to start improving this provider again soon, and then I'll add documentation on the resources too.

**Comment by btn-cai** [comment]
it may be possible to get started by referencing this file in tests: https://github.com/dihedron/terraform-provider-jenkins/blob/master/tests/main.tf

**Comment by dihedron** [comment]
@max-lobur @btn-cai I have updated the README, eventually.
